### ISSUE TITLE
harvesting, processing and selling not working

### ISSUE THREAD

**Issue by Itzmezzzzz** [ChrisToFLuA/tofdrugs#2]
i have all dependencies installed, but i didnt see any blip on harvest, processing and selling but i can teleport and use drugs can you help me with that also i got no errors

**Comment by ChrisToFLuA** [comment]
hello,
Step 1 : verifiy in your server.cfg that all dependencies start before the drugs script
Step 2 : verifiy that your not setjob police
Step 3 : put the script in your server.cfg (don't start it ingame)
Step 4 : restart your server and test it now

**Comment by ChrisToFLuA** [comment]
and download the dependencies with these links please :

ox_lib : [Release v2.11.1 · overextended/ox_lib · GitHub 2](https://github.com/overextended/ox_lib/releases/tag/v2.11.1)
qtarget : [Release 2.2.2 · overextended/qtarget · GitHub 2](https://github.com/overextended/qtarget/releases/tag/2.2.2)
polyzone : [Release v2.6.1 - BoxZone scale/offset, onPointInOut, and creation fixes · mkafrin/PolyZone · GitHub 3](https://github.com/mkafrin/PolyZone/releases/tag/v2.6.1)

**Comment by Itzmezzzzz** [comment]
tried all but npc selling works other than that nothing works

**Comment by ChrisToFLuA** [comment]
join the discord plz, and we will show this in vocal with stream, it will be more simple
i'll put the solution here then
https://discord.gg/B45FXcrqCt
